#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

if [ "$UNPROTECT_MASTER" = "1" ]; then
  exit 0
fi

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "master" ]; then
  echo "\e[31mThe master branch is a protected branch. Open a pull request instead.\e[0m"
  exit 1
fi
